force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/WaitingTime__c.field-meta.xml
<CustomField>
    <fullName>WaitingTime__c</fullName>
    <label>Waiting Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/File__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClientId</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LWC_WaitingClientsListController.cls
public without sharing class LWC_WaitingClientsListController {
    
    @AuraEnabled
    public static String getAllClients(){
        try {
            List<Client__c> clients = [
                SELECT Id, Name, WaitingTime__c, (
                    SELECT Id, Name, Size__c
                    FROM Files__r
                    ORDER BY Size__c ASC
                ),	
                Priority__c
                FROM Client__c
            ];

            return JSON.serialize(clients);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}