force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/WaitingTime__c.field-meta.xml
<CustomField>
    <fullName>WaitingTime__c</fullName>
    <label>Waiting Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config__c/fields/isSystemActive__c.field-meta.xml
<CustomField>
    <fullName>isSystemActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSystemActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/File__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClientId</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchMain.cls
public class BatchMain implements Database.Batchable<sObject>{
    String query;

    public BatchMain(){
        query = 'SELECT Id, Name, WaitingTime__c, (SELECT Id, Name, Size__c FROM Files__r ORDER BY Size__c ASC), Priority__c FROM Client__c';
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
  
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Client__c> clientList = (List<Client__c>) scope;

        for(Client__c client : clientList){
            client.WaitingTime__c++;
        }

        update clientList;
    }
  
    public void finish(Database.BatchableContext BC){
        DateTime startTime = System.Now();
        while(System.Now() < startTime.addseconds(3)) {}
        
        Config__c conf = [
            SELECT Id, isSystemActive__c
            FROM Config__c
            LIMIT 1
        ][0];

        if(conf.isSystemActive__c){
            Database.executeBatch(new BatchMain());
        }
    }
}