force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/FileId__c.field-meta.xml
<CustomField>
    <fullName>FileId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Id</label>
    <referenceTo>File__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClientId</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Server__c/Server__c.object-meta.xml
<CustomObject>
    <label>Server</label>
    <nameField>
        <label>Server Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Server__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Id</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Servers</relationshipLabel>
    <relationshipName>Servers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Server__c/fields/FileId__c.field-meta.xml
<CustomField>
    <fullName>FileId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Id</label>
    <referenceTo>File__c</referenceTo>
    <relationshipLabel>Servers</relationshipLabel>
    <relationshipName>Servers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Server__c/fields/FileProcessed__c.field-meta.xml
<CustomField>
    <fullName>FileProcessed__c</fullName>
    <formula>SizeProcessed__c  / FileId__r.Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File Processed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/LWC_ServersOverviewController.cls
public without sharing class LWC_ServersOverviewController {
    
    @AuraEnabled
    public static String getAllServers(){
        try {
            List<Server__c> servers = [
                SELECT Id, Name, ClientId__c, ClientId__r.Name, FileId__c, FileId__r.Name, FileId__r.Size__c, FileProcessed__c, isActive__c
                FROM Server__c
                ORDER BY Name
            ];

            return JSON.serialize(servers);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}