force-app/main/default/objects/File__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClientId</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LWC_ClientButtonsController.cls
public with sharing class LWC_ClientButtonsController {
    @AuraEnabled
    public static void addFile(Id clientId, String fileName){
        try {
            Integer randomNumber = Integer.valueof((math.random() * 10));
            File__c file = new File__c(Name=fileName, Size__c = Math.mod(randomNumber,60) + 1, ClientId__c = clientId);
            insert file;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}